# Generated by Django 3.0.8 on 2021-01-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_img', models.ImageField(upload_to='pics')),
                ('RAM', models.IntegerField(default=None)),
                ('ROM', models.IntegerField(default=None)),
                ('Cost', models.IntegerField(default=None)),
            ],
        ),
    ]
