# Generated by Django 3.0.8 on 2021-01-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='Link',
            field=models.URLField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='Name',
            field=models.CharField(default=0, max_length=70),
            preserve_default=False,
        ),
    ]
