# Generated by Django 3.0.8 on 2021-01-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0003_auto_20210130_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='para1',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='info',
            name='para2',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='info',
            name='para3',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='info',
            name='para4',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='info',
            name='para5',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='info',
            name='para6',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='info',
            name='para7',
            field=models.CharField(max_length=400),
        ),
    ]
