# Generated by Django 3.0.8 on 2021-01-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0005_auto_20210130_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='para7',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone_img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
